
#define CAT_ESS "必需品"
#define CAT_STD "标准装备"
#define CAT_SHO "鞋子"
#define CAT_HEL "帽子"
#define CAT_AMR "护甲"
#define CAT_GLO "手套"
#define CAT_EAR "耳"
#define CAT_BAK "背包"
#define CAT_POU "袋类"
#define CAT_WEB "织带"
#define CAT_BEL "腰带"
#define CAT_GLA "眼镜"
#define CAT_MAS "面具"
#define CAT_MOD "耶格存储模块"
#define CAT_ARMMOD "耶格尔装甲模块"

#define CAT_MEDSUP "医疗物资"
#define CAT_ENGSUP "工程物资"
#define CAT_LEDSUP "队长补给"
#define CAT_SGSUP "智能枪手补给"
#define CAT_FCSUP "指挥官补给"
#define CAT_LOAD "装备配置"

// Synth Special Categories
#define CAT_SMR "套装与护甲" // Synth's suits
#define CAT_SHN "帽子" // Synth's non-protective hats

#define VENDOR_FACTION_NEUTRAL "Neutral"
#define VENDOR_FACTION_CRASH "Crash"
#define VENDOR_FACTION_VALHALLA "Valhalla"

GLOBAL_LIST_INIT(marine_selector_cats, list(
		CAT_MOD = 1,
		CAT_ARMMOD = 1,
		CAT_STD = 1,
		CAT_SHO = 1,
		CAT_HEL = 1,
		CAT_AMR = 1,
		CAT_SMR = 1,
		CAT_SHN = 1,
		CAT_GLO = 1,
		CAT_EAR = 1,
		CAT_BAK = 1,
		CAT_WEB = 1,
		CAT_BEL = 1,
		CAT_GLA = 1,
		CAT_MAS = 1,
		CAT_ESS = 1,
		CAT_POU = 2,
	))

#define METAL_PRICE_IN_GEAR_VENDOR 2
#define PLASTEEL_PRICE_IN_GEAR_VENDOR 4
#define SANDBAG_PRICE_IN_GEAR_VENDOR 5

GLOBAL_LIST_INIT(marine_gear_listed_products, list())

GLOBAL_LIST_INIT(engineer_gear_listed_products, list(
		/obj/effect/vendor_bundle/engi = list(CAT_ESS, "基础工程师套装", 0, "white"),
		/obj/item/stack/sheet/metal/small_stack = list(CAT_ENGSUP, "金属 x10", METAL_PRICE_IN_GEAR_VENDOR, "engi-construction"),
		/obj/item/stack/sheet/plasteel/small_stack = list(CAT_ENGSUP, "塑钢 x10", PLASTEEL_PRICE_IN_GEAR_VENDOR, "engi-construction"),
		/obj/item/stack/sandbags_empty/half = list(CAT_ENGSUP, "沙袋 x25", SANDBAG_PRICE_IN_GEAR_VENDOR, "engi-construction"),
		/obj/item/weapon/shield/riot/marine/deployable = list(CAT_ENGSUP, "TL-182可部署护盾", 3, "engi-construction"),
		/obj/item/deployable_floodlight = list(CAT_ENGSUP, "可部署式泛光灯", 2, "engi-construction"),
		/obj/item/storage/pouch/explosive/razorburn = list(CAT_ENGSUP, "剃刀燃烧弹包", 11, "engi-construction"),
		/obj/item/explosive/grenade/chem_grenade/razorburn_large = list(CAT_ENGSUP, "剃须膏罐", 7, "engi-construction"),
		/obj/item/explosive/grenade/chem_grenade/razorburn_small = list(CAT_ENGSUP, "剃刀燃烧手榴弹", 3, "engi-construction"),
		/obj/item/deploy_capsule/barricade = list(CAT_ENGSUP, "路障胶囊", 18, "engi-construction"),
		/obj/item/tool/pickaxe/plasmacutter = list(CAT_ENGSUP, "等离子切割器", 20, "engi-tool"),
		/obj/item/tool/weldingtool/hugetank = list(CAT_ENGSUP, "高容量工业喷灯", 5, "engi-tool"),
		/obj/item/tool/handheld_charger = list(CAT_ENGSUP, "手持式电池充电器", 3, "engi-tool"),
		/obj/item/cell/rtg/large = list(CAT_ENGSUP, "大型充能器电池", 15, "engi-tool"),
		/obj/item/cell/rtg/small = list(CAT_ENGSUP, "充能器电源单元", 5, "engi-tool"),
		/obj/item/cell/high = list(CAT_ENGSUP, "高容量能量电池", 1, "engi-tool"),
		/obj/item/clothing/glasses/welding/superior = list(CAT_ENGSUP, "高级焊接护目镜", 2, "engi-tool"),
		/obj/item/armor_module/module/welding/superior = list(CAT_ENGSUP, "高级焊接模块", 2, "engi-tool"),
		/obj/item/explosive/plastique/genghis_charge = list(CAT_ENGSUP, "EX-62 成吉思燃烧弹", 15, "engi-explosive"),
		/obj/item/detpack = list(CAT_ENGSUP, "爆破包", 5, "engi-explosive"),
		/obj/item/explosive/plastique = list(CAT_ENGSUP, "塑性炸药", 2, "engi-explosive"),
		/obj/item/storage/box/explosive_mines/large = list(CAT_ENGSUP, "大型M20地雷箱", 35, "engi-explosive"),
		/obj/item/storage/box/explosive_mines = list(CAT_ENGSUP, "M20地雷箱", 18, "engi-explosive"),
		/obj/item/minelayer = list(CAT_ENGSUP, "M21 APRDS“布雷器”", 5, "engi-explosive"),
		/obj/item/storage/box/crate/minisentry = list(CAT_ENGSUP, "ST-580点防御哨戒炮套件", 40, "engi-other"),
		/obj/item/tesla_turret = list(CAT_ENGSUP, "特斯拉炮塔", 30, "engi-other"),
		/obj/structure/closet/crate/uav_crate = list(CAT_ENGSUP, "鬣蜥无人载具", 25, "engi-other"),
		/obj/structure/closet/crate/uav_crate/turret = list(CAT_ENGSUP, "轻型紫外线机枪", 15, "engi-other"),
		/obj/item/uav_turret/claw = list(CAT_ENGSUP, "紫外线爪", 5, "engi-other"),
		/obj/structure/closet/crate/uvt_crate = list(CAT_ENGSUP, "\"石龙子\"无人载具", 5, "engi-other"),
		/obj/item/attachable/buildasentry = list(CAT_ENGSUP, "组装哨兵配件", 30, "engi-other"),
		/obj/item/ammo_magazine/flamer_tank/large = list(CAT_ENGSUP, "火焰喷射器燃料罐", 4, "engi-other"),
		/obj/item/supply_beacon = list(CAT_ENGSUP, "补给信标", 5, "engi-other"),
		/obj/item/minerupgrade/overclock = list(CAT_ENGSUP, "矿井超频升级", 4, "engi-mining"),
		/obj/item/minerupgrade/reinforcement = list(CAT_ENGSUP, "矿井加固升级", 4, "engi-mining"),
		/obj/item/minerupgrade/automatic = list(CAT_ENGSUP, "矿井自动化升级", 4, "engi-mining"),
		/obj/item/binoculars/tactical/range = list(CAT_ENGSUP, "测距仪", 10, "engi-artillery"),
		/obj/item/ai_target_beacon = list(CAT_ENGSUP, "AI远程锁定模块", 10, "engi-artillery"),
		/obj/item/mortal_shell/he = list(CAT_ENGSUP, "高爆迫击炮弹", 2, "engi-artillery"),
		/obj/item/mortal_shell/incendiary = list(CAT_ENGSUP, "燃烧迫击炮弹", 2, "engi-artillery"),
		/obj/item/mortal_shell/plasmaloss = list(CAT_ENGSUP, "缠足迫击炮弹", 2, "engi-artillery"),
		/obj/item/mortal_shell/smoke = list(CAT_ENGSUP, "烟雾迫击炮弹", 1, "engi-artillery"),
		/obj/item/mortal_shell/flare = list(CAT_ENGSUP, "照明弹迫击炮弹", 1, "engi-artillery"),
	))

GLOBAL_LIST_INIT(medic_gear_listed_products, list(
		/obj/effect/vendor_bundle/medic = list(CAT_ESS, "基础医疗套装", 0, "white"),
		/obj/item/storage/pill_bottle/meralyne = list(CAT_MEDSUP, "梅拉琳药片", 16, "corps-meds"),
		/obj/item/storage/pill_bottle/dermaline = list(CAT_MEDSUP, "德玛林药片", 16, "corps-meds"),
		/obj/item/storage/syringe_case/meralyne = list(CAT_MEDSUP, "注射器盒（120单位梅拉林）", 16, "corps-meds"),
		/obj/item/reagent_containers/hypospray/advanced/meralyne = list(CAT_MEDSUP, "医用喷雾器（60单位梅拉林）", 8, "corps-meds"), //half the units of the mera case half the price
		/obj/item/storage/syringe_case/dermaline = list(CAT_MEDSUP, "注射器盒（120单位皮肤宁）", 16, "corps-meds"),
		/obj/item/reagent_containers/hypospray/advanced/dermaline = list(CAT_MEDSUP, "皮下注射器（60单位皮肤灵）", 8, "corps-meds"), //half the units of the derm case half the price
		/obj/item/storage/syringe_case/meraderm = list(CAT_MEDSUP, "注射器盒（120单位梅拉得姆）", 16, "corps-meds"),
		/obj/item/reagent_containers/hypospray/advanced/meraderm = list(CAT_MEDSUP, "医用喷雾器（60单位美拉达姆）", 8, "corps-meds"), //half the units of the meraderm case half the price
		/obj/item/storage/syringe_case/nanoblood = list(CAT_MEDSUP, "注射器盒（120单位纳米血液）", 5, "corps-meds"),
		/obj/item/reagent_containers/hypospray/advanced/nanoblood = list(CAT_MEDSUP, "注射器（60单位纳米血液）", 3, "corps-meds"), //bit more than half of the nanoblood case
		/obj/item/reagent_containers/hypospray/autoinjector/combat_advanced = list(CAT_MEDSUP, "注射器（高级）", 5, "corps-meds"),
		/obj/item/reagent_containers/hypospray/advanced/quickclotplus = list(CAT_MEDSUP, "注射器（速凝剂Plus）", 4, "corps-meds"),
		/obj/item/reagent_containers/hypospray/autoinjector/quickclotplus = list(CAT_MEDSUP, "注射器（速凝剂Plus）", 1, "corps-meds"),
		/obj/item/reagent_containers/hypospray/advanced/peridaxonplus = list(CAT_MEDSUP, "注射器（培里达松加强型）", 7, "corps-meds"),
		/obj/item/reagent_containers/hypospray/autoinjector/peridaxon_plus = list(CAT_MEDSUP, "注射器（培里达松加强型）", 1, "corps-meds"),
		/obj/item/reagent_containers/hypospray/autoinjector/synaptizine = list(CAT_MEDSUP, "注射器（突触素）", 4, "corps-meds"),
		/obj/item/reagent_containers/hypospray/autoinjector/neuraline = list(CAT_MEDSUP, "注射器（神经灵）", 14, "corps-meds"),
		/obj/item/explosive/grenade/chem_grenade/healing_foam = list(CAT_MEDSUP, "EMS-02 治疗泡沫手雷", 8, "corps-meds"),
		/obj/effect/vendor_bundle/stretcher = list(CAT_MEDSUP, "医疗运送担架", 45, "corps-tools"),
		/obj/item/reagent_containers/hypospray/advanced/big = list(CAT_MEDSUP, "大型注射器", 10, "corps-tools"),
		/obj/item/reagent_containers/hypospray/advanced = list(CAT_MEDSUP, "Hypospray", 2, "corps-tools"),
		/obj/item/clothing/glasses/hud/health = list(CAT_MEDSUP, "医疗HUD眼镜", 2, "corps-tools"),
		/obj/item/clothing/gloves/defibrillator = list(CAT_MEDSUP, "高级医疗手套", 5, "corps-tools"),
		/obj/item/clothing/gloves/healthanalyzer = list(CAT_MEDSUP, "健康扫描手套", 2, "corps-tools"),
		/obj/item/tweezers_advanced = list(CAT_MEDSUP, "破片钻头", 16, "corps-tools"),
	))

GLOBAL_LIST_INIT(leader_gear_listed_products, list(
		/obj/effect/vendor_bundle/leader = list(CAT_ESS, "基础SL套装", 0, "white"),
		/obj/item/whistle = list(CAT_LEDSUP, "Whistle", 5, "black"),
		/obj/item/supply_beacon = list(CAT_LEDSUP, "补给信标", 10, "black"),
		/obj/item/fulton_extraction_pack = list(CAT_LEDSUP, "富尔顿回收包", 20, "orange"),
		/obj/structure/closet/crate/uvt_crate = list(CAT_LEDSUP, "\"石龙子\"无人载具", 10, "orange"),
		/obj/item/deployable_camera = list(CAT_LEDSUP, "可部署监视摄像头", 2, "orange"),
		/obj/item/megaphone = list(CAT_LEDSUP, "Megaphone", 5, "orange"),
		/obj/item/stack/sandbags_empty/half = list(CAT_LEDSUP, "沙袋 x25", SANDBAG_PRICE_IN_GEAR_VENDOR, "black"),
		/obj/item/explosive/plastique = list(CAT_LEDSUP, "塑性炸药", 2, "black"),
		/obj/item/detpack = list(CAT_LEDSUP, "引爆背包", 5, "black"),
		/obj/structure/closet/bodybag/tarp = list(CAT_LEDSUP, "V1型热阻尼篷布", 5, "black"),
		/obj/item/explosive/grenade/smokebomb/cloak = list(CAT_LEDSUP, "斗篷手雷", 7, "black"),
		/obj/item/explosive/grenade/incendiary = list(CAT_LEDSUP, "M40 HIDP燃烧手榴弹", 3, "black"),
		/obj/item/storage/pouch/explosive/razorburn = list(CAT_LEDSUP, "剃刀燃烧弹包", 24, "orange"),
		/obj/item/storage/pouch/explosive/antigas = list(CAT_LEDSUP, "M40-AG防毒气榴弹包", 16, "orange"),
		/obj/item/explosive/grenade/chem_grenade/razorburn_large = list(CAT_LEDSUP, "剃须膏罐", 21, "black"),
		/obj/item/explosive/grenade/chem_grenade/razorburn_small = list(CAT_LEDSUP, "剃刀燃烧手榴弹", 6, "black"),
		/obj/item/weapon/gun/flamer/big_flamer/marinestandard = list(CAT_LEDSUP, "FL-84火焰喷射器", 12, "black"),
		/obj/item/ammo_magazine/flamer_tank/large = list(CAT_LEDSUP, "火焰喷射器燃料罐", 4, "black"),
		/obj/item/storage/backpack/marine/radiopack = list(CAT_LEDSUP, "无线电背包", 15, "black"),
		/obj/item/weapon/gun/revolver/standard_magnum = list(CAT_LEDSUP, "R-76麦格农", 12, "black"),
		/obj/item/reagent_containers/hypospray/autoinjector/synaptizine = list(CAT_LEDSUP, "注射器（突触素）", 10, "black"),
		/obj/item/reagent_containers/hypospray/autoinjector/combat_advanced = list(CAT_LEDSUP, "注射器（高级）", 15, "orange"),
	))

GLOBAL_LIST_INIT(commander_gear_listed_products, list(
		/obj/effect/vendor_bundle/commander = list(CAT_ESS, "基础FC套装", 0, "white"),
		/obj/item/whistle = list(CAT_FCSUP, "Whistle", 5, "black"),
		/obj/item/supply_beacon = list(CAT_FCSUP, "补给信标", 10, "black"),
		/obj/item/fulton_extraction_pack = list(CAT_FCSUP, "富尔顿回收包", 20, "orange"),
		/obj/structure/closet/crate/uvt_crate = list(CAT_FCSUP, "\"石龙子\"无人载具", 10, "orange"),
		/obj/item/deployable_camera = list(CAT_FCSUP, "可部署式监控摄像头", 2, "orange"),
		/obj/item/stack/sandbags_empty/half = list(CAT_FCSUP, "沙袋 x25", SANDBAG_PRICE_IN_GEAR_VENDOR, "black"),
		/obj/item/explosive/plastique = list(CAT_FCSUP, "塑胶炸药", 2, "black"),
		/obj/item/detpack = list(CAT_FCSUP, "爆破包", 5, "black"),
		/obj/structure/closet/bodybag/tarp = list(CAT_FCSUP, "V1型热阻尼帆布", 5, "black"),
		/obj/item/explosive/grenade/smokebomb/cloak = list(CAT_FCSUP, "斗篷手雷", 7, "black"),
		/obj/item/explosive/grenade/incendiary = list(CAT_FCSUP, "M40 HIDP燃烧手榴弹", 3, "black"),
		/obj/item/storage/pouch/explosive/razorburn = list(CAT_FCSUP, "剃刀燃烧弹包", 24, "orange"),
		/obj/item/storage/pouch/explosive/antigas = list(CAT_FCSUP, "M40-AG防毒气榴弹包", 16, "orange"),
		/obj/item/explosive/grenade/chem_grenade/razorburn_large = list(CAT_FCSUP, "剃须膏罐", 21, "black"),
		/obj/item/explosive/grenade/chem_grenade/razorburn_small = list(CAT_FCSUP, "剃刀燃烧手雷", 6, "black"),
		/obj/item/weapon/gun/flamer/big_flamer/marinestandard = list(CAT_FCSUP, "FL-84火焰喷射器", 12, "black"),
		/obj/item/ammo_magazine/flamer_tank/large = list(CAT_FCSUP, "火焰喷射器燃料罐", 4, "black"),
		/obj/item/storage/backpack/marine/radiopack = list(CAT_FCSUP, "无线电背包", 15, "black"),
		/obj/item/weapon/gun/revolver/standard_magnum = list(CAT_FCSUP, "R-76麦格农", 12, "black"),
		/obj/item/reagent_containers/hypospray/autoinjector/synaptizine = list(CAT_FCSUP, "注射器（突触素）", 10, "black"),
		/obj/item/reagent_containers/hypospray/autoinjector/combat_advanced = list(CAT_FCSUP, "注射器（高级）", 15, "orange"),
	))

//A way to give them everything at once that still works with loadouts would be nice, but barring that make sure that your point calculation is set up so they don't get more than what they're supposed to
GLOBAL_LIST_INIT(smartgunner_gear_listed_products, list(
	/obj/effect/vendor_bundle/smartgunner = list(CAT_ESS, "KLTD智能护目镜", 0, "white"),
	/obj/item/weapon/gun/rifle/standard_smartmachinegun = list(CAT_SGSUP, "SG-29 智能机枪", 29, "sg-machinegun"), //If a smartgunner buys a SG-29, then they will have 16 points to purchase 4 SG-29 drums
	/obj/item/ammo_magazine/standard_smartmachinegun = list(CAT_SGSUP, "SG-29 弹药鼓", 4, "sg-machinegun"),
	/obj/item/weapon/gun/minigun/smart_minigun = list(CAT_SGSUP, "SG-85智能手持加特林机枪", 27, "sg-minigun"), //If a smartgunner buys a SG-85, then they should be able to buy only 1 powerpack and 2 ammo bins
	/obj/item/ammo_magazine/minigun_powerpack/smartgun = list(CAT_SGSUP, "SG-85 能量包", 10, "sg-minigun"),
	/obj/item/ammo_magazine/packet/smart_minigun = list(CAT_SGSUP, "SG-85弹药箱", 4, "sg-minigun"),
	/obj/item/weapon/gun/rifle/standard_smarttargetrifle = list(CAT_SGSUP, "SG-62 目标步枪", 25, "sg-targetrifle"), //If a SG buys a SG-62, they'll have 15 points left, should be enough to buy some mags and or extra SR ammo.
	/obj/item/ammo_magazine/rifle/standard_smarttargetrifle = list(CAT_SGSUP, "SG-62 目标步枪弹匣", 3, "sg-targetrifle"),
	/obj/item/ammo_magazine/packet/smart_targetrifle = list(CAT_SGSUP, "SG-62 目标步枪弹药箱", 4, "sg-targetrifle"),
	/obj/item/ammo_magazine/packet/smart_spottingrifle = list(CAT_SGSUP, "SG-153 观测步枪弹药箱", 4, "sg-targetrifle"),
	/obj/item/ammo_magazine/rifle/standard_spottingrifle = list(CAT_SGSUP, "SG-153 观测步枪弹匣", 2, "sg-targetrifle"),
	/obj/item/ammo_magazine/rifle/standard_spottingrifle/highimpact = list(CAT_SGSUP, "SG-153 观测步枪高冲击弹匣", 2, "sg-targetrifle"),
	/obj/item/ammo_magazine/rifle/standard_spottingrifle/heavyrubber = list(CAT_SGSUP, "SG-153 观测步枪重型橡胶弹匣", 2, "sg-targetrifle"),
	/obj/item/ammo_magazine/rifle/standard_spottingrifle/tungsten = list(CAT_SGSUP, "SG-153 观测步枪钨制弹匣", 2, "sg-targetrifle"),
	/obj/item/ammo_magazine/rifle/standard_spottingrifle/flak = list(CAT_SGSUP, "SG-153 观测步枪防空弹匣", 2, "sg-targetrifle"),
	/obj/item/ammo_magazine/rifle/standard_spottingrifle/plasmaloss = list(CAT_SGSUP, "SG-153 观测步枪缠足弹匣", 3, "sg-targetrifle"),
	/obj/item/ammo_magazine/rifle/standard_spottingrifle/incendiary = list(CAT_SGSUP, "SG-153 观测步枪燃烧弹匣", 3, "sg-targetrifle"),
	))


///Assoc list linking the job title with their specific points vendor
GLOBAL_LIST_INIT(job_specific_points_vendor, list(
	SQUAD_MARINE = GLOB.marine_gear_listed_products,
	SQUAD_ENGINEER = GLOB.engineer_gear_listed_products,
	SQUAD_CORPSMAN = GLOB.medic_gear_listed_products,
	SQUAD_LEADER = GLOB.leader_gear_listed_products,
	FIELD_COMMANDER = GLOB.commander_gear_listed_products,
	SQUAD_SMARTGUNNER = GLOB.smartgunner_gear_listed_products,
))


//List of all visible and accessible slot on the loadout maker
GLOBAL_LIST_INIT(visible_item_slot_list, list(
	slot_head_str,
	slot_back_str,
	slot_wear_mask_str,
	slot_glasses_str,
	slot_w_uniform_str,
	slot_wear_suit_str,
	slot_gloves_str,
	slot_shoes_str,
	slot_s_store_str,
	slot_belt_str,
	slot_l_store_str,
	slot_r_store_str,
))

///List of all additional item slot used by the admin loadout build mode
GLOBAL_LIST_INIT(additional_admin_item_slot_list, list(
	slot_l_hand_str,
	slot_r_hand_str,
	slot_wear_id_str,
	slot_ear_str,
))

///All the vendor types which the automated loadout vendor can take items from.
GLOBAL_LIST_INIT(loadout_linked_vendor, list(
	VENDOR_FACTION_NEUTRAL = list(
		/obj/machinery/vending/weapon,
		/obj/machinery/vending/uniform_supply,
		/obj/machinery/vending/armor_supply,
		/obj/machinery/vending/marineFood,
		/obj/machinery/vending/MarineMed,
		/obj/machinery/vending/cigarette,
		/obj/machinery/vending/tool,
	),
	VENDOR_FACTION_VALHALLA = list(
		/obj/machinery/vending/weapon/valhalla,
		/obj/machinery/vending/uniform_supply/valhalla,
		/obj/machinery/vending/armor_supply/valhalla,
		/obj/machinery/vending/marineFood,
		/obj/machinery/vending/MarineMed/valhalla,
		/obj/machinery/vending/cigarette/valhalla,
		/obj/machinery/vending/tool/nopower/valhalla,
	),
	SQUAD_CORPSMAN = list(
		/obj/machinery/vending/medical/shipside,
	),
	VENDOR_FACTION_CRASH = list(
		/obj/machinery/vending/weapon/crash,
		/obj/machinery/vending/uniform_supply,
		/obj/machinery/vending/armor_supply,
		/obj/machinery/vending/marineFood,
		/obj/machinery/vending/MarineMed,
		/obj/machinery/vending/cigarette,
		/obj/machinery/vending/tool,
	)
))

GLOBAL_LIST_INIT(marine_clothes_listed_products, list(
		/obj/effect/vendor_bundle/basic = list(CAT_STD, "标准套件", 0, "white"),
		/obj/effect/vendor_bundle/basic_jaeger = list(CAT_STD, "耶格尔基础套装", 0, "white"),
		/obj/effect/vendor_bundle/robot/essentials = list(CAT_STD, "基础战斗机器人套件", 0, "white"),
		/obj/effect/vendor_bundle/xenonauten_light = list(CAT_AMR, "异星战士轻型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/xenonauten_medium = list(CAT_AMR, "异星战士中型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/xenonauten_heavy = list(CAT_AMR, "异星战士重型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_light = list(CAT_AMR, "耶格尔侦察兵轻型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_skirmish = list(CAT_AMR, "耶格尔轻骑兵轻型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_infantry = list(CAT_AMR, "耶格尔步兵中型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_eva = list(CAT_AMR, "耶格尔EVA中型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_hell_jumper = list(CAT_AMR, "耶格尔地狱跳跃者中型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_ranger = list(CAT_AMR, "耶格尔游侠中型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_gungnir = list(CAT_AMR, "耶格尔·冈格尼尔重型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_assault = list(CAT_AMR, "耶格尔突击重型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_eod = list(CAT_AMR, "耶格尔重型拆弹护甲套装", 0, "orange"),
		/obj/item/clothing/suit/modular/rownin = list(CAT_AMR, "罗温骨架", 0, "black"),
		/obj/effect/vendor_bundle/robot/light_armor = list(CAT_AMR, "战斗机器人轻型装甲套件", 0, "black"),
		/obj/effect/vendor_bundle/robot/medium_armor = list(CAT_AMR, "中型战斗机器人装甲套件", 0, "black"),
		/obj/effect/vendor_bundle/robot/heavy_armor = list(CAT_AMR, "战斗机器人重型装甲套件", 0, "black"),
		/obj/item/storage/backpack/marine/satchel = list(CAT_BAK, "Satchel", 0, "orange"),
		/obj/item/storage/backpack/marine/standard = list(CAT_BAK, "Backpack", 0, "black"),
		/obj/item/armor_module/storage/uniform/black_vest = list(CAT_WEB, "战术黑色背心", 0, "orange"),
		/obj/item/armor_module/storage/uniform/webbing = list(CAT_WEB, "战术携行具", 0, "black"),
		/obj/item/armor_module/storage/uniform/holster = list(CAT_WEB, "肩挂手枪枪套", 0, "black"),
		/obj/item/storage/belt/sparepouch = list(CAT_BEL, "工具腰带", 0, "black"),
		/obj/item/storage/belt/marine = list(CAT_BEL, "标准弹药带", 0, "orange"),
		/obj/item/storage/belt/shotgun = list(CAT_BEL, "霰弹枪弹药带", 0, "orange"),
		/obj/item/storage/belt/knifepouch = list(CAT_BEL, "刀具腰带", 0, "black"),
		/obj/item/storage/holster/belt/pistol/standard_pistol = list(CAT_BEL, "手枪腰带", 0, "black"),
		/obj/item/storage/holster/belt/revolver/standard_revolver = list(CAT_BEL, "左轮手枪腰带", 0, "black"),
		/obj/item/belt_harness/marine = list(CAT_BEL, "束带背带", 0, "black"),
		/obj/item/armor_module/module/welding = list(CAT_HEL, "耶格焊接模块", 0, "orange"),
		/obj/item/armor_module/module/binoculars = list(CAT_HEL, "耶格尔双目镜模块", 0, "orange"),
		/obj/item/armor_module/module/artemis = list(CAT_HEL, "耶格尔-弗雷尔模块", 0, "orange"),
		/obj/item/armor_module/module/antenna = list(CAT_HEL, "耶格尔天线模块", 0, "orange"),
		/obj/item/armor_module/storage/medical = list(CAT_MOD, "医疗存储模块", 0, "black"),
		/obj/item/armor_module/storage/injector = list(CAT_MOD, "注射器储存模块", 0, "black"),
		/obj/item/armor_module/storage/general = list(CAT_MOD, "通用存储模块", 0, "black"),
		/obj/item/armor_module/storage/engineering = list(CAT_MOD, "工程存储模块", 0, "black"),
		/obj/item/armor_module/storage/grenade = list(CAT_MOD, "榴弹存储模块", 0, "black"),
		/obj/item/storage/pouch/shotgun = list(CAT_POU, "霰弹枪弹袋", 0, "black"),
		/obj/item/storage/pouch/magazine/large = list(CAT_POU, "弹匣袋", 0, "black"),
		/obj/item/storage/holster/flarepouch/full = list(CAT_POU, "信号弹袋", 0, "orange"),
		/obj/item/storage/pouch/medkit/firstaid = list(CAT_POU, "急救包", 0,"orange"),
		/obj/item/storage/pouch/medical_injectors/standard = list(CAT_POU, "战斗注射器包", 0,"orange"),
		/obj/item/storage/pouch/tools/full = list(CAT_POU, "工具袋（内含工具）", 0,"black"),
		/obj/item/storage/pouch/grenade/slightlyfull = list(CAT_POU, "手榴弹袋（含手榴弹）", 0,"black"),
		/obj/item/storage/pouch/construction/full = list(CAT_POU, "施工袋（内含材料）", 0,"black"),
		/obj/item/storage/pouch/magazine/pistol/large = list(CAT_POU, "手枪弹匣袋", 0,"black"),
		/obj/item/storage/pouch/pistol = list(CAT_POU, "手枪套", 0,"black"),
		/obj/effect/vendor_bundle/mimir = list(CAT_ARMMOD, "马克1型密米尔抗性套装", 0,"black"),
		/obj/effect/vendor_bundle/tyr = list(CAT_ARMMOD, "马克1型泰尔强化护甲套装", 0,"black"),
		/obj/item/armor_module/module/ballistic_armor = list(CAT_ARMMOD, "霍德防事故镀层", 0,"black"),
		/obj/item/armor_module/module/better_shoulder_lamp = list(CAT_ARMMOD, "巴尔德轻型护甲模块", 0,"black"),
		/obj/effect/vendor_bundle/vali = list(CAT_ARMMOD, "瓦利化学强化套装", 0,"black"),
		/obj/item/armor_module/module/eshield = list(CAT_ARMMOD, "斯瓦林能量护盾系统", 0 , "black"),
		/obj/item/armor_module/module/mirage = list(CAT_ARMMOD, "洛基幻象模块", 0, "black"),
		/obj/item/armor_module/module/armorlock = list(CAT_ARMMOD, "雷神装甲锁模块", 0, "black"),
		/obj/item/clothing/mask/gas = list(CAT_MAS, "透明防毒面具", 0,"black"),
		/obj/item/clothing/mask/gas/tactical = list(CAT_MAS, "战术防毒面具", 0,"black"),
		/obj/item/clothing/mask/gas/tactical/coif = list(CAT_MAS, "战术头罩式防毒面具", 0,"black"),
		/obj/item/clothing/mask/rebreather/scarf = list(CAT_MAS, "吸热头巾", 0,"black"),
		/obj/item/clothing/mask/rebreather = list(CAT_MAS, "Rebreather", 0,"black"),
		/obj/item/clothing/mask/bandanna = list(CAT_MAS, "棕色头巾", 0,"black"),
		/obj/item/clothing/mask/bandanna/green = list(CAT_MAS, "绿色头巾", 0,"black"),
		/obj/item/clothing/mask/bandanna/white = list(CAT_MAS, "白色头巾", 0,"black"),
		/obj/item/clothing/mask/bandanna/black = list(CAT_MAS, "黑色头巾", 0,"black"),
		/obj/item/clothing/mask/bandanna/skull = list(CAT_MAS, "骷髅头巾", 0,"black"),
	))

GLOBAL_LIST_INIT(engineer_clothes_listed_products, list(
		/obj/effect/vendor_bundle/basic_engineer = list(CAT_STD, "标准套件", 0, "white"),
		/obj/effect/vendor_bundle/basic_jaeger_engineer = list(CAT_STD, "耶格尔基础套装", 0, "white"),
		/obj/effect/vendor_bundle/robot/essentials = list(CAT_STD, "基础战斗机器人套件", 0, "white"),
		/obj/item/clothing/glasses/welding = list(CAT_GLA, "焊接护目镜", 0, "white"),
		/obj/item/clothing/glasses/meson = list(CAT_GLA, "光学介子扫描仪", 0, "white"),
		/obj/effect/vendor_bundle/robot/light_armor = list(CAT_AMR, "战斗机器人轻型装甲套件", 0, "black"),
		/obj/effect/vendor_bundle/robot/medium_armor = list(CAT_AMR, "中型战斗机器人装甲套件", 0, "black"),
		/obj/effect/vendor_bundle/robot/heavy_armor = list(CAT_AMR, "战斗机器人重型装甲套件", 0, "black"),
		/obj/effect/vendor_bundle/xenonauten_light = list(CAT_AMR, "异星战士轻型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/xenonauten_medium = list(CAT_AMR, "异星战士中型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/xenonauten_heavy = list(CAT_AMR, "异星战士重型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_light = list(CAT_AMR, "耶格尔侦察兵轻型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_skirmish = list(CAT_AMR, "耶格尔轻骑兵轻型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_infantry = list(CAT_AMR, "耶格尔步兵中型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_eva = list(CAT_AMR, "耶格尔EVA中型装甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_hell_jumper = list(CAT_AMR, "耶格尔地狱跳跃者中型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_ranger = list(CAT_AMR, "耶格尔游侠中型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_gungnir = list(CAT_AMR, "耶格尔·冈格尼尔重型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_assault = list(CAT_AMR, "耶格尔突击重型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_eod = list(CAT_AMR, "耶格尔重型拆弹防护套装", 0, "orange"),
		/obj/item/storage/backpack/marine/satchel/tech = list(CAT_BAK, "Satchel", 0, "orange"),
		/obj/item/storage/backpack/marine/tech = list(CAT_BAK, "技师背包", 0, "black"),
		/obj/item/storage/holster/blade/machete/full = list(CAT_BAK, "砍刀刀鞘", 0, "black"),
		/obj/item/storage/backpack/marine/engineerpack = list(CAT_BAK, "Welderpack", 0, "black"),
		/obj/item/storage/backpack/marine/radiopack = list(CAT_BAK, "无线电背包", 0, "black"),
		/obj/item/storage/backpack/dispenser = list(CAT_BAK, "Dispenser", 0, "black"),
		/obj/item/storage/holster/backholster/mortar/full = list(CAT_BAK, "迫击炮包", 0, "black"),
		/obj/item/storage/holster/backholster/flamer/full = list(CAT_BAK, "火焰喷射器背包", 0, "black"),
		/obj/item/armor_module/storage/uniform/brown_vest = list(CAT_WEB, "战术棕色背心", 0, "orange"),
		/obj/item/armor_module/storage/uniform/webbing = list(CAT_WEB, "战术携行带", 0, "black"),
		/obj/item/armor_module/storage/uniform/holster = list(CAT_WEB, "肩挂手枪套", 0, "black"),
		/obj/item/storage/belt/utility/full = list(CAT_BEL, "工具腰带", 0, "white"),
		/obj/item/armor_module/module/welding = list(CAT_HEL, "耶格焊接模块", 0, "orange"),
		/obj/item/armor_module/module/binoculars = list(CAT_HEL, "\"耶格尔\"双筒望远镜模块", 0, "orange"),
		/obj/item/armor_module/module/artemis = list(CAT_HEL, "耶格尔·弗雷尔模块", 0, "orange"),
		/obj/item/armor_module/module/antenna = list(CAT_HEL, "耶格尔天线模块", 0, "orange"),
		/obj/item/clothing/head/beret/eng = list(CAT_HEL, "工程贝雷帽", 0, "black"),
		/obj/item/armor_module/storage/medical = list(CAT_MOD, "医疗存储模块", 0, "black"),
		/obj/item/armor_module/storage/injector = list(CAT_MOD, "注射器存储模块", 0, "black"),
		/obj/item/armor_module/storage/general = list(CAT_MOD, "通用存储模块", 0, "black"),
		/obj/item/armor_module/storage/engineering = list(CAT_MOD, "工程存储模块", 0, "black"),
		/obj/item/armor_module/storage/grenade = list(CAT_MOD, "手榴弹存储模块", 0, "black"),
		/obj/item/storage/pouch/shotgun = list(CAT_POU, "霰弹枪弹袋", 0, "black"),
		/obj/item/storage/pouch/construction/full = list(CAT_POU, "施工包（内含材料）", 0, "orange"),
		/obj/item/storage/pouch/explosive = list(CAT_POU, "炸药袋", 0, "black"),
		/obj/item/storage/pouch/tools/full = list(CAT_POU, "工具袋", 0, "black"),
		/obj/item/storage/pouch/grenade/slightlyfull = list(CAT_POU, "手榴弹袋（内含手榴弹）", 0,"black"),
		/obj/item/storage/pouch/electronics/full = list(CAT_POU, "电子元件袋", 0, "black"),
		/obj/item/storage/pouch/magazine/large = list(CAT_POU, "弹匣包", 0, "black"),
		/obj/item/storage/pouch/general/medium = list(CAT_POU, "中型通用袋", 0, "black"),
		/obj/item/storage/holster/flarepouch/full = list(CAT_POU, "信号弹袋", 0, "black"),
		/obj/item/storage/pouch/medkit/firstaid = list(CAT_POU, "急救包", 0, "orange"),
		/obj/item/storage/pouch/medical_injectors/standard = list(CAT_POU, "战斗注射器包", 0, "orange"),
		/obj/item/storage/pouch/magazine/pistol/large = list(CAT_POU, "手枪弹匣袋", 0, "black"),
		/obj/item/storage/pouch/pistol = list(CAT_POU, "手枪套", 0, "black"),
		/obj/effect/vendor_bundle/mimir = list(CAT_ARMMOD, "马克1型密米尔抗性套装", 0,"black"),
		/obj/item/armor_module/module/ballistic_armor = list(CAT_ARMMOD, "霍德防事故镀层", 0,"black"),
		/obj/effect/vendor_bundle/tyr = list(CAT_ARMMOD, "马克1型泰尔强化护甲套装", 0,"black"),
		/obj/item/armor_module/module/better_shoulder_lamp = list(CAT_ARMMOD, "巴尔德轻型护甲模块", 0,"black"),
		/obj/effect/vendor_bundle/vali = list(CAT_ARMMOD, "瓦利化学强化套装", 0,"black"),
		/obj/item/armor_module/module/eshield = list(CAT_ARMMOD, "斯瓦林能量护盾系统", 0 , "black"),
		/obj/item/armor_module/module/mirage = list(CAT_ARMMOD, "洛基幻象模块", 0, "black"),
		/obj/item/armor_module/module/armorlock = list(CAT_ARMMOD, "雷神装甲锁定模块", 0, "black"),
		/obj/item/clothing/mask/gas = list(CAT_MAS, "透明防毒面具", 0,"black"),
		/obj/item/clothing/mask/gas/tactical = list(CAT_MAS, "战术防毒面具", 0,"black"),
		/obj/item/clothing/mask/gas/tactical/coif = list(CAT_MAS, "战术头罩式防毒面具", 0,"black"),
		/obj/item/clothing/mask/rebreather/scarf = list(CAT_MAS, "吸热头巾", 0, "black"),
		/obj/item/clothing/mask/rebreather = list(CAT_MAS, "Rebreather", 0, "black"),
	))

GLOBAL_LIST_INIT(medic_clothes_listed_products, list(
		/obj/effect/vendor_bundle/basic_medic = list(CAT_STD, "标准套件", 0, "white"),
		/obj/effect/vendor_bundle/basic_jaeger_medic = list(CAT_STD, "耶格尔基础装备包", 0, "white"),
		/obj/effect/vendor_bundle/robot/essentials = list(CAT_STD, "基础战斗机器人套件", 0, "white"),
		/obj/effect/vendor_bundle/xenonauten_light = list(CAT_AMR, "异星战士轻型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/xenonauten_medium = list(CAT_AMR, "异星战士中型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/xenonauten_heavy = list(CAT_AMR, "异星战士重型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_light = list(CAT_AMR, "耶格尔侦察兵轻型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_skirmish = list(CAT_AMR, "耶格尔轻骑兵轻型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_infantry = list(CAT_AMR, "耶格尔步兵中型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_eva = list(CAT_AMR, "耶格尔EVA中型装甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_hell_jumper = list(CAT_AMR, "耶格尔地狱跳跃者中型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_ranger = list(CAT_AMR, "耶格尔游侠中型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_gungnir = list(CAT_AMR, "耶格尔·冈格尼尔重型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_assault = list(CAT_AMR, "\"耶格尔\"突击重型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_eod = list(CAT_AMR, "耶格尔重型拆弹护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/robot/light_armor = list(CAT_AMR, "战斗机器人轻型装甲套件", 0, "black"),
		/obj/effect/vendor_bundle/robot/medium_armor = list(CAT_AMR, "中型战斗机器人装甲套件", 0, "black"),
		/obj/effect/vendor_bundle/robot/heavy_armor = list(CAT_AMR, "战斗机器人重型装甲套件", 0, "black"),
		/obj/item/storage/backpack/marine/corpsman/satchel = list(CAT_BAK, "Satchel", 0, "orange"),
		/obj/item/storage/backpack/marine/corpsman = list(CAT_BAK, "验尸官背包", 0, "black"),
		/obj/item/armor_module/storage/uniform/brown_vest = list(CAT_WEB, "战术棕色背心", 0, "orange"),
		/obj/item/armor_module/storage/uniform/white_vest = list(CAT_WEB, "医护兵白色背心", 0, "black"),
		/obj/item/armor_module/storage/uniform/webbing = list(CAT_WEB, "战术携行带", 0, "black"),
		/obj/item/armor_module/storage/uniform/holster = list(CAT_WEB, "肩挂手枪枪套", 0, "black"),
		/obj/item/storage/belt/lifesaver/full = list(CAT_BEL, "救生腰带", 0, "orange"),
		/obj/item/storage/belt/rig/medical = list(CAT_BEL, "装备腰带", 0, "black"),
		/obj/item/storage/belt/hypospraybelt/full = list(CAT_BEL, "注射带", 0, "black"),
		/obj/item/armor_module/module/welding = list(CAT_HEL, "耶格焊接模块", 0, "orange"),
		/obj/item/armor_module/module/binoculars = list(CAT_HEL, "\"耶格尔\"双筒望远镜模块", 0, "orange"),
		/obj/item/armor_module/module/artemis = list(CAT_HEL, "耶格尔-弗雷尔模块", 0, "orange"),
		/obj/item/armor_module/module/artemis = list(CAT_HEL, "耶格尔-弗雷尔模块", 0, "orange"),
		/obj/item/armor_module/module/antenna = list(CAT_HEL, "耶格尔天线模块", 0, "orange"),
		/obj/item/armor_module/storage/medical = list(CAT_MOD, "医疗存储模块", 0, "black"),
		/obj/item/armor_module/storage/injector = list(CAT_MOD, "注射器存储模块", 0, "black"),
		/obj/item/armor_module/storage/general = list(CAT_MOD, "通用存储模块", 0, "black"),
		/obj/item/armor_module/storage/engineering = list(CAT_MOD, "工程存储模块", 0, "black"),
		/obj/item/armor_module/storage/grenade = list(CAT_MOD, "手榴弹存储模块", 0, "black"),
		/obj/item/storage/pouch/medical_injectors/medic = list(CAT_POU, "高级自动注射器包", 0, "orange"),
		/obj/item/storage/pouch/medkit/medic = list(CAT_POU, "医疗包袋", 0, "orange"),
		/obj/item/storage/pouch/construction/full = list(CAT_POU, "施工包（内含材料）", 0, "orange"),
		/obj/effect/vendor_bundle/mimir = list(CAT_ARMMOD, "马克1型密米尔抗性套装", 0,"black"),
		/obj/item/armor_module/module/ballistic_armor = list(CAT_ARMMOD, "霍德防事故镀层", 0,"black"),
		/obj/effect/vendor_bundle/tyr = list(CAT_ARMMOD, "马克1型泰尔强化护甲套装", 0,"black"),
		/obj/item/armor_module/module/better_shoulder_lamp = list(CAT_ARMMOD, "博德轻型护甲模块", 0,"black"),
		/obj/effect/vendor_bundle/vali = list(CAT_ARMMOD, "瓦利化学强化套装", 0,"black"),
		/obj/item/armor_module/module/eshield = list(CAT_ARMMOD, "斯瓦林能量护盾系统", 0 , "black"),
		/obj/item/armor_module/module/mirage = list(CAT_ARMMOD, "洛基幻象模块", 0, "black"),
		/obj/item/armor_module/module/armorlock = list(CAT_ARMMOD, "雷神装甲锁定模块", 0, "black"),
		/obj/item/clothing/mask/gas = list(CAT_MAS, "透明防毒面具", 0,"black"),
		/obj/item/clothing/mask/gas/tactical = list(CAT_MAS, "战术防毒面具", 0,"black"),
		/obj/item/clothing/mask/gas/tactical/coif = list(CAT_MAS, "战术头罩式防毒面具", 0,"black"),
		/obj/item/clothing/mask/rebreather/scarf = list(CAT_MAS, "吸热头巾", 0, "black"),
		/obj/item/clothing/mask/rebreather = list(CAT_MAS, "Rebreather", 0, "black"),
	))

GLOBAL_LIST_INIT(smartgunner_clothes_listed_products, list(
		/obj/effect/vendor_bundle/basic_smartgunner = list(CAT_STD, "标准套件", 0, "white"),
		/obj/effect/vendor_bundle/basic_jaeger_smartgunner = list(CAT_STD, "耶格尔基础装备包", 0, "white"),
		/obj/effect/vendor_bundle/robot/essentials_smartgunner = list(CAT_STD, "基础战斗机器人套件", 0, "white"),
		/obj/effect/vendor_bundle/xenonauten_light = list(CAT_AMR, "异星战士轻型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/xenonauten_medium = list(CAT_AMR, "异星战士中型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/xenonauten_heavy = list(CAT_AMR, "异星战士重型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_light = list(CAT_AMR, "耶格尔侦察兵轻型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_skirmish = list(CAT_AMR, "耶格尔轻骑兵轻型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_infantry = list(CAT_AMR, "耶格尔步兵中型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_eva = list(CAT_AMR, "耶格尔EVA中型装甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_hell_jumper = list(CAT_AMR, "耶格尔地狱跳跃者中型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_ranger = list(CAT_AMR, "耶格尔游侠中型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_gungnir = list(CAT_AMR, "耶格尔·冈格尼尔重型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_assault = list(CAT_AMR, "耶格尔突击重型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_eod = list(CAT_AMR, "耶格尔重型拆弹护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/robot/light_armor = list(CAT_AMR, "战斗机器人轻型护甲套件", 0, "black"),
		/obj/effect/vendor_bundle/robot/medium_armor = list(CAT_AMR, "中型战斗机器人装甲套件", 0, "black"),
		/obj/effect/vendor_bundle/robot/heavy_armor = list(CAT_AMR, "战斗机器人重型装甲套件", 0, "black"),
		/obj/item/armor_module/storage/uniform/black_vest = list(CAT_WEB, "战术黑色背心", 0, "orange"),
		/obj/item/armor_module/storage/uniform/webbing = list(CAT_WEB, "战术携行带", 0, "black"),
		/obj/item/armor_module/storage/uniform/holster = list(CAT_WEB, "肩挂手枪枪套", 0, "black"),
		/obj/item/storage/belt/marine = list(CAT_BEL, "标准弹药带", 0, "black"),
		/obj/item/storage/belt/shotgun = list(CAT_BEL, "霰弹枪弹药带", 0, "black"),
		/obj/item/storage/belt/knifepouch = list(CAT_BEL, "刀具腰带", 0, "black"),
		/obj/item/storage/holster/belt/pistol/standard_pistol = list(CAT_BEL, "手枪腰带", 0, "orange"),
		/obj/item/storage/holster/belt/revolver/standard_revolver = list(CAT_BEL, "左轮手枪腰带", 0, "orange"),
		/obj/item/storage/belt/sparepouch = list(CAT_BEL, "G8通用工具袋", 0, "orange"),
		/obj/item/armor_module/module/welding = list(CAT_HEL, "耶格焊接模块", 0, "orange"),
		/obj/item/armor_module/module/binoculars = list(CAT_HEL, "\"耶格尔\"双筒望远镜模块", 0, "orange"),
		/obj/item/armor_module/module/artemis = list(CAT_HEL, "耶格尔-弗雷尔模块", 0, "orange"),
		/obj/item/armor_module/module/antenna = list(CAT_HEL, "耶格尔天线模块", 0, "orange"),
		/obj/item/armor_module/storage/medical = list(CAT_MOD, "医疗存储模块", 0, "black"),
		/obj/item/armor_module/storage/injector = list(CAT_MOD, "注射器存储模块", 0, "black"),
		/obj/item/armor_module/storage/general = list(CAT_MOD, "通用存储模块", 0, "black"),
		/obj/item/armor_module/storage/engineering = list(CAT_MOD, "工程存储模块", 0, "black"),
		/obj/item/armor_module/storage/grenade = list(CAT_MOD, "榴弹存储模块", 0, "black"),
		/obj/item/storage/pouch/shotgun = list(CAT_POU, "霰弹枪弹袋", 0, "black"),
		/obj/item/storage/pouch/grenade/slightlyfull = list(CAT_POU, "手榴弹袋（含手榴弹）", 0,"black"),
		/obj/item/storage/pouch/magazine/large = list(CAT_POU, "弹匣袋", 0, "black"),
		/obj/item/storage/pouch/general/medium = list(CAT_POU, "中型通用袋", 0, "black"),
		/obj/item/storage/holster/flarepouch/full = list(CAT_POU, "信号弹袋", 0, "orange"),
		/obj/item/storage/pouch/medical_injectors/standard = list(CAT_POU, "战斗注射器包", 0,"orange"),
		/obj/item/storage/pouch/medkit/firstaid = list(CAT_POU, "急救包", 0, "orange"),
		/obj/item/storage/pouch/magazine/pistol/large = list(CAT_POU, "手枪弹匣袋", 0, "black"),
		/obj/item/storage/pouch/pistol = list(CAT_POU, "手枪套", 0, "black"),
		/obj/item/storage/pouch/construction/full = list(CAT_POU, "施工腰包（含材料）", 0, "orange"),
		/obj/effect/vendor_bundle/mimir = list(CAT_ARMMOD, "马克1型密米尔抗性套装", 0,"black"),
		/obj/effect/vendor_bundle/tyr = list(CAT_ARMMOD, "马克1型泰尔强化护甲套装", 0,"black"),
		/obj/item/armor_module/module/better_shoulder_lamp = list(CAT_ARMMOD, "巴尔德轻型护甲模块", 0,"black"),
		/obj/effect/vendor_bundle/vali = list(CAT_ARMMOD, "瓦利化学强化套装", 0,"black"),
		/obj/item/clothing/mask/gas = list(CAT_MAS, "透明防毒面具", 0,"black"),
		/obj/item/clothing/mask/gas/tactical = list(CAT_MAS, "战术防毒面具", 0,"black"),
		/obj/item/clothing/mask/gas/tactical/coif = list(CAT_MAS, "战术头罩式防毒面具", 0,"black"),
		/obj/item/clothing/mask/rebreather/scarf = list(CAT_MAS, "吸热头巾", 0, "black"),
		/obj/item/clothing/mask/rebreather = list(CAT_MAS, "Rebreather", 0, "black"),
	))

GLOBAL_LIST_INIT(leader_clothes_listed_products, list(
		/obj/effect/vendor_bundle/basic_squadleader = list(CAT_STD, "标准套件", 0, "white"),
		/obj/effect/vendor_bundle/basic_jaeger_squadleader = list(CAT_STD, "耶格尔基础装备包", 0, "white"),
		/obj/effect/vendor_bundle/robot/essentials = list(CAT_STD, "基础战斗机器人套件", 0, "white"),
		/obj/effect/vendor_bundle/xenonauten_light/leader = list(CAT_AMR, "异星战士轻型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/xenonauten_medium/leader = list(CAT_AMR, "异星战士中型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/xenonauten_heavy/leader = list(CAT_AMR, "异星战士重型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_light = list(CAT_AMR, "耶格尔侦察兵轻型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_skirmish = list(CAT_AMR, "耶格尔轻骑兵轻型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_infantry = list(CAT_AMR, "耶格尔步兵中型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_eva = list(CAT_AMR, "耶格尔EVA中型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_hell_jumper = list(CAT_AMR, "耶格尔地狱跳跃者中型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_ranger = list(CAT_AMR, "耶格尔游侠中型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_gungnir = list(CAT_AMR, "耶格尔·冈格尼尔重型护甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_assault = list(CAT_AMR, "\"耶格尔\"突击重型护甲套件", 0, "orange"),
		/obj/effect/vendor_bundle/jaeger_eod = list(CAT_AMR, "耶格尔重型拆弹装甲套装", 0, "orange"),
		/obj/effect/vendor_bundle/robot/light_armor = list(CAT_AMR, "战斗机器人轻型装甲套件", 0, "black"),
		/obj/effect/vendor_bundle/robot/medium_armor = list(CAT_AMR, "中型战斗机器人装甲套件", 0, "black"),
		/obj/effect/vendor_bundle/robot/heavy_armor = list(CAT_AMR, "战斗机器人重型装甲套件", 0, "black"),
		/obj/item/storage/backpack/marine/satchel = list(CAT_BAK, "Satchel", 0, "black"),
		/obj/item/storage/backpack/marine/standard = list(CAT_BAK, "Backpack", 0, "black"),
		/obj/item/storage/holster/blade/machete/full = list(CAT_BAK, "砍刀鞘", 0, "black"),
		/obj/item/storage/backpack/marine/radiopack = list(CAT_BAK, "无线电背包", 0, "black"),
		/obj/item/armor_module/storage/uniform/black_vest = list(CAT_WEB, "战术黑色背心", 0, "black"),
		/obj/item/armor_module/storage/uniform/webbing = list(CAT_WEB, "战术携行带", 0, "black"),
		/obj/item/armor_module/storage/uniform/holster = list(CAT_WEB, "肩挂手枪枪套", 0, "black"),
		/obj/item/storage/belt/marine = list(CAT_BEL, "标准弹药带", 0, "black"),
		/obj/item/storage/belt/shotgun = list(CAT_BEL, "霰弹枪弹药带", 0, "black"),
		/obj/item/storage/belt/knifepouch = list(CAT_BEL, "刀具腰带", 0, "black"),
		/obj/item/storage/holster/belt/pistol/standard_pistol = list(CAT_BEL, "手枪腰带", 0, "black"),
		/obj/item/storage/holster/belt/revolver/standard_revolver = list(CAT_BEL, "左轮手枪腰带", 0, "black"),
		/obj/item/storage/belt/sparepouch = list(CAT_BEL, "G8通用工具袋", 0, "black"),
		/obj/item/belt_harness/marine = list(CAT_BEL, "腰带式背带", 0, "black"),
		/obj/item/armor_module/module/welding = list(CAT_HEL, "耶格焊接模块", 0, "orange"),
		/obj/item/armor_module/module/binoculars = list(CAT_HEL, "耶格尔双目镜模块", 0, "orange"),
		/obj/item/armor_module/module/artemis = list(CAT_HEL, "耶格尔-弗雷尔模块", 0, "orange"),
		/obj/item/armor_module/module/antenna = list(CAT_HEL, "耶格尔天线模块", 0, "orange"),
		/obj/item/armor_module/storage/medical = list(CAT_MOD, "医疗存储模块", 0, "black"),
		/obj/item/armor_module/storage/injector = list(CAT_MOD, "注射器存储模块", 0, "black"),
		/obj/item/armor_module/storage/general = list(CAT_MOD, "通用存储模块", 0, "black"),
		/obj/item/armor_module/storage/engineering = list(CAT_MOD, "工程存储模块", 0, "black"),
		/obj/item/armor_module/storage/grenade = list(CAT_MOD, "榴弹存储模块", 0, "black"),
		/obj/item/storage/pouch/shotgun = list(CAT_POU, "霰弹枪弹袋", 0, "black"),
		/obj/item/storage/pouch/general/large = list(CAT_POU, "通用袋", 0, "black"),
		/obj/item/storage/pouch/magazine/large = list(CAT_POU, "弹匣包", 0, "black"),
		/obj/item/storage/holster/flarepouch/full = list(CAT_POU, "信号弹袋", 0, "black"),
		/obj/item/storage/pouch/medical_injectors/standard = list(CAT_POU, "战斗注射器包", 0,"orange"),
		/obj/item/storage/pouch/medkit/firstaid = list(CAT_POU, "急救包", 0, "orange"),
		/obj/item/storage/pouch/tools/full = list(CAT_POU, "工具袋（内含工具）", 0, "black"),
		/obj/item/storage/pouch/grenade/slightlyfull = list(CAT_POU, "手榴弹袋（内含手榴弹）", 0,"black"),
		/obj/item/storage/pouch/construction/full = list(CAT_POU, "施工腰包（内含材料）", 0, "black"),
		/obj/item/storage/pouch/magazine/pistol/large = list(CAT_POU, "手枪弹匣袋", 0, "black"),
		/obj/item/storage/pouch/pistol = list(CAT_POU, "手枪套", 0, "black"),
		/obj/item/storage/pouch/explosive = list(CAT_POU, "爆炸袋", 0, "black"),
		/obj/effect/vendor_bundle/mimir = list(CAT_ARMMOD, "马克1型密米尔抗性套装", 0,"black"),
		/obj/effect/vendor_bundle/tyr = list(CAT_ARMMOD, "马克1型泰尔强化护甲套装", 0,"black"),
		/obj/item/armor_module/module/ballistic_armor = list(CAT_ARMMOD, "霍德防事故镀层", 0,"black"),
		/obj/item/armor_module/module/better_shoulder_lamp = list(CAT_ARMMOD, "巴尔德轻型护甲模块", 0,"black"),
		/obj/effect/vendor_bundle/vali = list(CAT_ARMMOD, "瓦利化学强化套装", 0,"black"),
		/obj/item/armor_module/module/eshield = list(CAT_ARMMOD, "斯瓦林能量护盾系统", 0 , "black"),
		/obj/item/armor_module/module/mirage = list(CAT_ARMMOD, "洛基幻象模块", 0, "black"),
		/obj/item/armor_module/module/armorlock = list(CAT_ARMMOD, "雷神装甲锁模块", 0, "black"),
		/obj/item/clothing/mask/gas = list(CAT_MAS, "透明防毒面具", 0,"black"),
		/obj/item/clothing/mask/gas/tactical = list(CAT_MAS, "战术防毒面具", 0,"black"),
		/obj/item/clothing/mask/gas/tactical/coif = list(CAT_MAS, "战术头罩式防毒面具", 0,"black"),
		/obj/item/clothing/mask/rebreather/scarf = list(CAT_MAS, "吸热头巾", 0, "black"),
		/obj/item/clothing/mask/rebreather = list(CAT_MAS, "Rebreather", 0, "black"),
	))

GLOBAL_LIST_INIT(synthetic_clothes_listed_products, list(
		/obj/effect/vendor_bundle/synth = list(CAT_ESS, "基础合成套装", 0, "white"),
		/obj/item/clothing/glasses/meson = list(CAT_GLA, "光学介子扫描仪", 0, "white"),
		/obj/item/clothing/under/marine = list(CAT_STD, "TGMC陆战队制服", 0, "black"),
		/obj/item/clothing/under/rank/medical/blue = list(CAT_STD, "医用刷手服（蓝色）", 0, "black"),
		/obj/item/clothing/under/rank/medical/green = list(CAT_STD, "医用刷手服（绿色）", 0, "black"),
		/obj/item/clothing/under/rank/medical/purple = list(CAT_STD, "医用刷手服（紫色）", 0, "black"),
		/obj/item/clothing/under/marine/officer/engi = list(CAT_STD, "工程制服", 0, "black"),
		/obj/item/clothing/under/marine/officer/pilot = list(CAT_STD, "飞行员连体服", 0, "black"),
		/obj/item/clothing/under/marine/mp = list(CAT_STD, "宪兵制服", 0, "black"),
		/obj/item/clothing/under/marine/officer/researcher = list(CAT_STD, "研究员制服", 0, "black"),
		/obj/item/clothing/under/rank/chef = list(CAT_STD, "厨师制服", 0, "black"),
		/obj/item/clothing/under/rank/bartender = list(CAT_STD, "酒保制服", 0, "black"),
		/obj/item/clothing/under/rank/chef/altchef = list(CAT_STD, "红色厨师制服", 0, "black"),
		/obj/item/clothing/under/rank/janitor = list(CAT_STD, "清洁工制服", 0, "black"),
		/obj/item/clothing/under/rank/det = list(CAT_STD, "侦探制服", 0, "black"),
		/obj/item/clothing/under/rank/dispatch = list(CAT_STD, "调度员制服", 0, "black"),
		/obj/item/clothing/under/overalls = list(CAT_STD, "Overalls", 0, "black"),
		/obj/item/clothing/under/CM_uniform = list(CAT_STD, "殖民地警长制服", 0, "black"),
		/obj/item/clothing/under/gentlesuit = list(CAT_STD, "绅士西装", 0, "black"),
		/obj/item/clothing/under/sl_suit = list(CAT_STD, "阿米什套装", 0, "black"),
		/obj/item/clothing/under/waiter = list(CAT_STD, "服务员制服", 0, "black"),
		/obj/item/clothing/suit/modular/xenonauten/pilot = list(CAT_SMR, "M70防弹背心", 0, "synth-rcmarmstorage"),
		/obj/item/clothing/suit/armor/bulletproof = list(CAT_SMR, "防弹背心", 0, "synth-armor"),
		/obj/item/clothing/suit/surgical = list(CAT_SMR, "手术围裙", 0, "synth-cosmetic"),
		/obj/item/clothing/suit/storage/labcoat = list(CAT_SMR, "Labcoat", 0, "synth-cosmetic"),
		/obj/item/clothing/suit/storage/labcoat/paramedic = list(CAT_SMR, "急救员实验袍", 0, "synth-cosmetic"),
		/obj/item/clothing/suit/storage/hazardvest = list(CAT_SMR, "橙色反光安全背心", 0, "synth-cosmetic"),
		/obj/item/clothing/suit/storage/hazardvest/lime = list(CAT_SMR, "青柠色反光安全背心", 0, "synth-cosmetic"),
		/obj/item/clothing/suit/storage/hazardvest/blue = list(CAT_SMR, "蓝色反光安全背心", 0, "synth-cosmetic"),
		/obj/item/clothing/suit/storage/CMB = list(CAT_SMR, "CMB夹克", 0, "synth-cosmetic"),
		/obj/item/clothing/suit/storage/RO = list(CAT_SMR, "TGMC RO夹克", 0, "synth-cosmetic"),
		/obj/item/clothing/suit/storage/lawyer/bluejacket = list(CAT_SMR, "蓝色夹克", 0, "synth-cosmetic"),
		/obj/item/clothing/suit/storage/lawyer/purpjacket = list(CAT_SMR, "紫色夹克", 0, "synth-cosmetic"),
		/obj/item/clothing/suit/storage/snow_suit = list(CAT_SMR, "Snowsuit", 0, "synth-cosmetic"),
		/obj/item/clothing/suit/storage/chef = list(CAT_SMR, "厨师围裙", 0, "synth-storage"),
		/obj/item/clothing/suit/storage/wizrobe/gentlecoat = list(CAT_SMR, "绅士外套", 0, "synth-storage"),
		/obj/item/clothing/suit/storage/bomber = list(CAT_SMR, "轰炸机夹克", 0, "synth-storage"),
		/obj/item/clothing/suit/storage/security/formal/senior_officer = list(CAT_SMR, "海军安保部长夹克", 0, "synth-storage"),
		/obj/item/clothing/suit/storage/chef/classic = list(CAT_SMR, "经典厨师背心", 0, "synth-storage"),
		/obj/item/clothing/suit/storage/apron = list(CAT_SMR, "Apron", 0, "synth-storage"),
		/obj/item/clothing/suit/storage/apron/overalls = list(CAT_SMR, "Overalls", 0, "synth-storage"),
		/obj/item/clothing/suit/wcoat = list(CAT_SMR, "Waistcoat", 0, "synth-cosmetic"),
		/obj/item/clothing/suit/ianshirt = list(CAT_SMR, "伊恩衬衫", 0, "synth-cosmetic"),
		/obj/item/clothing/suit/suspenders = list(CAT_SMR, "Suspenders", 0, "synth-cosmetic"),
		/obj/item/storage/backpack/marine/corpsman = list(CAT_BAK, "TGMC医护兵背包", 0, "black"),
		/obj/item/storage/backpack/marine/tech = list(CAT_BAK, "TGMC技术员背包", 0, "black"),
		/obj/item/storage/backpack/marine/engineerpack = list(CAT_BAK, "TGMC技师焊枪背包", 0, "black"),
		/obj/item/storage/backpack/marine/radiopack = list(CAT_BAK, "无线电背包", 0, "black"),
		/obj/item/storage/backpack/lightpack = list(CAT_BAK, "轻型战斗背包", 0, "black"),
		/obj/item/storage/backpack/marine/satchel/officer_cloak = list(CAT_BAK, "军官斗篷", 0, "black"),
		/obj/item/storage/backpack/marine/satchel/officer_cloak_red = list(CAT_BAK, "警官斗篷，红色", 0, "black"),
		/obj/item/armor_module/storage/uniform/webbing = list(CAT_WEB, "Webbing", 0, "black"),
		/obj/item/armor_module/storage/uniform/black_vest = list(CAT_WEB, "战术黑色背心", 0, "black"),
		/obj/item/armor_module/storage/uniform/white_vest = list(CAT_WEB, "白色医疗背心", 0, "black"),
		/obj/item/armor_module/storage/uniform/surgery_webbing = list(CAT_WEB, "白色手术绷带", 0, "black"),
		/obj/item/clothing/gloves/insulated = list(CAT_GLO, "绝缘手套", 0, "black"),
		/obj/item/clothing/gloves/marine = list(CAT_GLO, "战斗手套", 0, "synth-armor"),
		/obj/item/clothing/gloves/latex = list(CAT_GLO, "乳胶手套", 0, "black"),
		/obj/item/storage/belt/lifesaver/full = list(CAT_BEL, "救生腰带", 0, "orange", "synth-attachable"),
		/obj/item/storage/belt/rig/medical = list(CAT_BEL, "装备腰带", 0, "black"),
		/obj/item/storage/belt/hypospraybelt/full = list(CAT_BEL, "注射腰带", 0, "black"),
		/obj/item/clothing/shoes/marine = list(CAT_SHO, "陆战队作战靴", 0, "synth-rcmarmor"),
		/obj/item/clothing/shoes/white = list(CAT_SHO, "白色鞋子", 0, "synth-armor"),
		/obj/item/clothing/shoes/brown = list(CAT_SHO, "棕色鞋子", 0, "synth-armor"),
		/obj/item/clothing/shoes/leather = list(CAT_SHO, "皮鞋", 0, "synth-armor"),
		/obj/item/clothing/shoes/centcom = list(CAT_SHO, "正装鞋", 0, "synth-armor"),
		/obj/item/clothing/shoes/black = list(CAT_SHO, "黑色鞋子", 0, "synth-armor"),
		/obj/item/storage/pouch/tools/full = list(CAT_POU, "工具袋", 0, "black"),
		/obj/item/storage/pouch/construction/full = list(CAT_POU, "施工包（内含材料）", 0, "black"),
		/obj/item/storage/pouch/medkit/doctor = list(CAT_POU, "医疗包袋", 0, "black"),
		/obj/item/storage/pouch/surgery = list(CAT_POU, "白色手术包", 0, "black"),
		/obj/item/storage/pouch/field_pouch/full = list(CAT_POU, "野战挎包", 0, "black"),
		/obj/item/clothing/head/modular/style/cap = list(CAT_SHN, "TGMC军帽", 0, "synth-rcmarmstorage"),
		/obj/item/clothing/head/modular/style/boonie = list(CAT_SHN, "奔尼帽", 0, "synth-rcmarmstorage"),
		/obj/item/clothing/head/modular/style/classic_beret = list(CAT_SHN, "海军贝雷帽", 0, "synth-rcmarmstorage"),
		/obj/item/clothing/head/modular/style/ushanka = list(CAT_SHN, "Ushanka", 0, "synth-rcmarmstorage"),
		/obj/item/clothing/head/modular/style/beanie = list(CAT_SHN, "Beanie", 0, "synth-rcmarmstorage"),
		/obj/item/clothing/head/hardhat = list(CAT_SHN, "安全帽", 0, "black"),
		/obj/item/clothing/head/welding = list(CAT_SHN, "焊接头盔", 0, "black"),
		/obj/item/clothing/head/surgery/green = list(CAT_SHN, "手术帽", 0, "black"),
		/obj/item/clothing/head/collectable/tophat = list(CAT_SHN, "高顶礼帽", 0, "black"),
		/obj/item/clothing/head/bowlerhat = list(CAT_SHN, "圆顶礼帽", 0, "black"),
		/obj/item/clothing/head/hairflower = list(CAT_SHN, "发簪", 0, "black"),
		/obj/item/clothing/head/fez = list(CAT_SHN, "Fez", 0, "black"),
		/obj/item/clothing/head/chefhat = list(CAT_SHN, "厨师帽", 0, "black"),
		/obj/item/clothing/head/beaverhat = list(CAT_HEL, "海狸皮帽", 0, "black"),
		/obj/item/clothing/mask/surgical = list(CAT_MAS, "无菌口罩", 0, "black"),
		/obj/item/clothing/mask/rebreather = list(CAT_MAS, "Rebreather", 0, "black"),
		/obj/item/clothing/mask/rebreather/scarf = list(CAT_MAS, "吸热头巾", 0, "black"),
		/obj/item/clothing/mask/gas = list(CAT_MAS, "透明防毒面具", 0,"black"),
		/obj/item/clothing/mask/gas/tactical = list(CAT_MAS, "战术防毒面具", 0,"black"),
		/obj/item/clothing/mask/gas/tactical/coif = list(CAT_MAS, "战术头罩式防毒面具", 0,"black"),
	))

///Assoc list linking the job title with their specific clothes vendor
GLOBAL_LIST_INIT(job_specific_clothes_vendor, list(
	SQUAD_MARINE = GLOB.marine_clothes_listed_products,
	SQUAD_ENGINEER = GLOB.engineer_clothes_listed_products,
	SQUAD_CORPSMAN = GLOB.medic_clothes_listed_products,
	SQUAD_SMARTGUNNER = GLOB.smartgunner_clothes_listed_products,
	SQUAD_LEADER = GLOB.leader_clothes_listed_products,
	SYNTHETIC = GLOB.synthetic_clothes_listed_products,
))

GLOBAL_LIST_INIT(loadout_role_essential_set, list(
	SQUAD_ENGINEER = list (
		/obj/item/explosive/plastique = 1,
		/obj/item/explosive/grenade/chem_grenade/razorburn_small = 1,
		/obj/item/clothing/gloves/marine/insulated = 1,
		/obj/item/cell/high = 1,
		/obj/item/lightreplacer = 1,
		/obj/item/circuitboard/apc = 1,
		/obj/item/clothing/under/marine/engineer = 1,
	),
	SQUAD_CORPSMAN = list(
		/obj/item/bodybag/cryobag = 1,
		/obj/item/defibrillator = 1,
		/obj/item/healthanalyzer = 1,
		/obj/item/roller/medevac = 1,
		/obj/item/medevac_beacon = 1,
		/obj/item/roller = 1,
		/obj/item/tweezers = 1,
		/obj/item/reagent_containers/hypospray/advanced/oxycodone = 1,
		/obj/item/clothing/glasses/hud/health = 1,
		/obj/item/clothing/under/marine/corpsman = 1,
	),
	SQUAD_SMARTGUNNER = list(
		/obj/item/clothing/glasses/night/m56_goggles = 1,
	),
	SQUAD_LEADER = list(
		/obj/item/explosive/plastique = 1,
		/obj/item/supply_beacon = 2,
		/obj/item/whistle = 1,
		/obj/item/binoculars/tactical = 1,
		/obj/item/pinpointer = 1,
		/obj/item/clothing/glasses/hud/health = 1,
		/obj/item/clothing/head/modular/m10x/leader = 1,
	),
	FIELD_COMMANDER = list(
		/obj/item/explosive/plastique = 1,
		/obj/item/supply_beacon = 1,
		/obj/item/healthanalyzer = 1,
		/obj/item/roller/medevac = 1,
		/obj/item/medevac_beacon = 1,
		/obj/item/whistle = 1,
		/obj/item/clothing/glasses/hud/health = 1,
	),
	SYNTHETIC = list(
		/obj/item/stack/sheet/plasteel/medium_stack = 1,
		/obj/item/stack/sheet/metal/large_stack = 1,
		/obj/item/tool/weldingtool/hugetank = 1,
		/obj/item/tool/handheld_charger = 1,
		/obj/item/defibrillator = 1,
		/obj/item/medevac_beacon = 1,
		/obj/item/roller/medevac = 1,
		/obj/item/roller = 1,
		/obj/item/bodybag/cryobag = 1,
		/obj/item/reagent_containers/hypospray/advanced/oxycodone = 1,
		/obj/item/tweezers = 1,
		/obj/item/cell/high = 1,
		/obj/item/circuitboard/apc = 1,
		/obj/item/tool/soap = 1,
	)
))

///Storage items that will always have their default content
GLOBAL_LIST_INIT(loadout_instantiate_default_contents, typecacheof(list(
	/obj/item/storage/box/MRE,
	/obj/item/storage/pill_bottle,
	/obj/item/storage/box/m94,
	/obj/item/storage/fancy/chemrettes,
	/obj/item/storage/fancy/cigarettes,
)))

//Defines use for the visualisation of loadouts
#define NO_OFFSET "0%"
#define NO_SCALING 1
#define MODULAR_ARMOR_OFFSET_Y "-10%"
#define MODULAR_ARMOR_SCALING 1.2

///The maximum number of loadouts one player can have
#define MAXIMUM_LOADOUT 50

/// The current loadout version
#define CURRENT_LOADOUT_VERSION 16

GLOBAL_LIST_INIT(accepted_loadout_versions, list(5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16))
